### ISSUE TITLE
Running AppEngine download on Ubuntu 22.04 x64 system (error: 'You incorrectly pinned it to debian-openssl-3.0.x')

### ISSUE THREAD

**Issue by BitOneZero1** [Nectres/animos#24]
```
$ ./Animos-0.2.2.AppImage 
{ loadPath: [AsyncFunction (anonymous)] }
api started listening
{
  preloadPath: '/tmp/.mount_AnimosqTwH2h/resources/app.asar/dist/electron-src/preload.js',
  iconPath: '/tmp/.mount_AnimosqTwH2h/resources/app.asar/build/icons/favicon.ico'
}
(node:160836) UnhandledPromiseRejectionWarning: Error: Query engine library for current platform "debian-openssl-3.0.x" could not be found.
You incorrectly pinned it to debian-openssl-3.0.x

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/tmp/.mount_AnimosqTwH2h/resources/node_modules/@prisma/client/runtime/libquery_engine-debian-openssl-3.0.x.so.node")

Searched Locations:

  /tmp/.mount_AnimosqTwH2h/resources/node_modules/.prisma/client
  /home/runner/work/animos/animos/node_modules/@prisma/client
  /tmp/.mount_AnimosqTwH2h/resources/node_modules/@prisma/client
  /tmp/.mount_AnimosqTwH2h/resources/node_modules/.prisma/client
  /tmp/.mount_AnimosqTwH2h/resources/prisma
  /tmp/prisma-engines
  /tmp/.mount_AnimosqTwH2h/resources/node_modules/.prisma/client


To solve this problem, add the platform "debian-openssl-3.0.x" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
    at DefaultLibraryLoader.getLibQueryEnginePath (/tmp/.mount_AnimosqTwH2h/resources/node_modules/@prisma/client/runtime/index.js:30092:13)
    at async DefaultLibraryLoader.loadLibrary (/tmp/.mount_AnimosqTwH2h/resources/node_modules/@prisma/client/runtime/index.js:30010:33)
    at async LibraryEngine.loadEngine (/tmp/.mount_AnimosqTwH2h/resources/node_modules/@prisma/client/runtime/index.js:30328:24)
    at async LibraryEngine.instantiateLibrary (/tmp/.mount_AnimosqTwH2h/resources/node_modules/@prisma/client/runtime/index.js:30286:5)
(Use `animos --trace-warnings ...` to show where the warning was created)
(node:160836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Error occurred in handler for 'home:get-poster': PrismaClientInitializationError: 
Invalid `db_1.prisma.poster.findMany()` invocation in
/tmp/.mount_AnimosqTwH2h/resources/app.asar/dist/electron-src/ipc.js:58:61

  55 var posters, data;
  56 return __generator(this, function (_a) {
  57     switch (_a.label) {
→ 58         case 0: return [4 /*yield*/, db_1.prisma.poster.findMany(
```

**Comment by thaYt** [comment]
hey, you're using an old release of animos here. can you try launching with the [latest release](https://github.com/Nectres/animos/releases) and see if the issue still happens?
